#!/usr/bin/env bash
# DBWCARE Board – Lokale Full-Stack-Entwicklungsumgebung
# Backend (Docker) + Frontend (pnpm dev) auf localhost.
#
# Usage:
#   ./dev-local.sh up       – Backend-Compose + Frontend starten
#   ./dev-local.sh down     – Backend-Compose stoppen
#   ./dev-local.sh logs [s] – Logs eines Backend-Services tailen
#   ./dev-local.sh migrate  – Django-Migrations ausfuehren
#   ./dev-local.sh shell    – Django-Shell oeffnen
#   ./dev-local.sh seed     – Demo-Daten anlegen
#   ./dev-local.sh reset    – Volumes loeschen & neu starten

set -euo pipefail
cd "$(dirname "$0")"

# ── Farben ──────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

COMPOSE_FILE="docker-compose.dbwcare-local.yml"
ENV_FILE=".env.dbwcare-local"

# ── Hilfsfunktionen ────────────────────────────────────────────────────

dc() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

check_env() {
  if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}Fehler: $ENV_FILE nicht gefunden!${NC}"
    echo "Kopiere .env.dbwcare-local.example zu $ENV_FILE:"
    echo "  cp .env.dbwcare-local.example $ENV_FILE"
    exit 1
  fi
}

write_frontend_env() {
  # Frontend .env fuer lokales Backend (localhost:8000 statt Hetzner)
  for app in apps/web apps/admin apps/space; do
    cat > "${app}/.env" <<ENVEOF
# Auto-generated by dev-local.sh – DO NOT COMMIT
# Pointing to LOCAL backend (docker-compose.dbwcare-local.yml)
DEV_API_PROXY_TARGET=http://localhost:8000
VITE_API_BASE_URL=
VITE_WEB_BASE_URL=http://localhost:3000
VITE_ADMIN_BASE_URL=http://localhost:3001
VITE_ADMIN_BASE_PATH=/god-mode
VITE_SPACE_BASE_URL=http://localhost:3002
VITE_SPACE_BASE_PATH=/spaces
VITE_LIVE_BASE_URL=http://localhost:3100
VITE_LIVE_BASE_PATH=/live
ENVEOF
    echo -e "${GREEN}✓${NC} ${app}/.env geschrieben (lokal)"
  done

  # Live-Service .env (laeuft via pnpm dev, braucht localhost Redis + API)
  cat > apps/live/.env <<ENVEOF
# Auto-generated by dev-local.sh – DO NOT COMMIT
PORT=3100
API_BASE_URL=http://localhost:8000
WEB_BASE_URL=http://localhost:3000
LIVE_BASE_URL=http://localhost:3100
LIVE_BASE_PATH=/live
LIVE_SERVER_SECRET_KEY=local-dev-live-secret
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_URL=redis://localhost:6379/
ENVEOF
  echo -e "${GREEN}✓${NC} apps/live/.env geschrieben (lokal)"
}

wait_for_api() {
  echo -e "${YELLOW}Warte auf API (localhost:8000)...${NC}"
  local retries=60
  while [ $retries -gt 0 ]; do
    if curl -sf http://localhost:8000/api/v1/config/ > /dev/null 2>&1; then
      echo -e "${GREEN}✓${NC} API ist bereit"
      return 0
    fi
    retries=$((retries - 1))
    sleep 2
  done
  echo -e "${YELLOW}API antwortet noch nicht auf /api/v1/config/ – starte Frontend trotzdem${NC}"
}

# ── Commands ────────────────────────────────────────────────────────────

cmd_up() {
  check_env

  echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║  DBWCARE BOARD – Lokales Full-Stack      ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"

  # Backend starten
  echo -e "\n${BLUE}→${NC} Starte Backend-Services (Docker)..."
  dc up -d --build

  # Frontend .env schreiben
  write_frontend_env

  # Warten bis API bereit
  wait_for_api

  # pnpm install falls noetig
  if [ ! -d node_modules ]; then
    echo -e "${BLUE}→${NC} node_modules fehlt, starte pnpm install..."
    pnpm install
  fi

  # Frontend starten
  echo ""
  echo -e "${GREEN}Starte Frontend Dev-Server...${NC}"
  echo -e "  ${RED}web${NC}   → http://localhost:3000"
  echo -e "  ${BLUE}admin${NC} → http://localhost:3001/god-mode"
  echo -e "  ${YELLOW}space${NC} → http://localhost:3002/spaces"
  echo -e "  ${GREEN}api${NC}   → http://localhost:8000 (Docker)"
  echo -e "  ${GREEN}live${NC}  → http://localhost:3100 (pnpm dev)"
  echo ""

  pnpm dev
}

cmd_down() {
  check_env
  echo -e "${BLUE}→${NC} Stoppe Backend-Services..."
  dc down
  echo -e "${GREEN}✓${NC} Backend gestoppt"
}

cmd_logs() {
  check_env
  local service="${1:-}"
  if [ -z "$service" ]; then
    dc logs -f
  else
    dc logs -f "$service"
  fi
}

cmd_migrate() {
  check_env
  echo -e "${BLUE}→${NC} Fuehre Migrations aus..."
  dc exec api python manage.py migrate --settings=plane.settings.local
  echo -e "${GREEN}✓${NC} Migrations abgeschlossen"
}

cmd_shell() {
  check_env
  dc exec api python manage.py shell --settings=plane.settings.local
}

cmd_seed() {
  check_env
  echo -e "${BLUE}→${NC} Seede Demo-Daten..."
  dc exec api python manage.py seed_dbwcare --settings=plane.settings.local
  echo -e "${GREEN}✓${NC} Demo-Daten angelegt"
}

cmd_reset() {
  check_env
  echo -e "${RED}ACHTUNG: Alle lokalen Daten (Postgres, Redis, Minio) werden geloescht!${NC}"
  read -p "Bist du sicher? (y/N) " confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    echo "Abgebrochen."
    exit 0
  fi
  echo -e "${BLUE}→${NC} Stoppe und loesche Volumes..."
  dc down -v
  echo -e "${GREEN}✓${NC} Volumes geloescht"
  echo -e "${BLUE}→${NC} Starte neu..."
  cmd_up
}

# ── Main ────────────────────────────────────────────────────────────────

case "${1:-help}" in
  up)      cmd_up ;;
  down)    cmd_down ;;
  logs)    shift; cmd_logs "$@" ;;
  migrate) cmd_migrate ;;
  shell)   cmd_shell ;;
  seed)    cmd_seed ;;
  reset)   cmd_reset ;;
  help|*)
    echo "Usage: ./dev-local.sh <command>"
    echo ""
    echo "Commands:"
    echo "  up       Starte Backend (Docker) + Frontend (pnpm dev)"
    echo "  down     Stoppe Backend-Services"
    echo "  logs [s] Zeige Logs (optional: Service-Name)"
    echo "  migrate  Django-Migrations ausfuehren"
    echo "  shell    Django-Shell oeffnen"
    echo "  seed     Demo-Daten anlegen (User, Workspace, Subscription)"
    echo "  reset    Volumes loeschen & komplett neu starten"
    ;;
esac
