#!/usr/bin/env bash
# DBWCARE Board – Lokale Full-Stack-Entwicklungsumgebung
# Backend (Docker) + Frontend (pnpm dev) auf localhost.
#
# Usage:
#   ./dev-local.sh up       – Backend-Compose + Frontend starten
#   ./dev-local.sh down     – Backend-Compose stoppen
#   ./dev-local.sh logs [s] – Logs eines Backend-Services tailen
#   ./dev-local.sh migrate  – Django-Migrations ausfuehren
#   ./dev-local.sh shell    – Django-Shell oeffnen
#   ./dev-local.sh seed     – Demo-Daten anlegen
#   ./dev-local.sh reset    – Volumes loeschen & neu starten

set -euo pipefail
cd "$(dirname "$0")"

# ── Farben ──────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

COMPOSE_FILE="docker-compose.dbwcare-local.yml"
ENV_FILE=".env.dbwcare-local"

# ── Hilfsfunktionen ────────────────────────────────────────────────────

dc() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

check_env() {
  if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}Fehler: $ENV_FILE nicht gefunden!${NC}"
    echo "Kopiere .env.dbwcare-local.example zu $ENV_FILE:"
    echo "  cp .env.dbwcare-local.example $ENV_FILE"
    exit 1
  fi
}

write_frontend_env() {
  # Frontend .env fuer lokales Backend (localhost:8000 statt Hetzner)
  # WICHTIG: Auch .env.local loeschen/ueberschreiben, da Vite diese
  # mit hoeherer Prioritaet liest und dev.sh dort ggf. Hetzner-URL hinterlassen hat.
  for app in apps/web apps/admin apps/space; do
    # .env.local entfernen (Vite liest sie vor .env)
    rm -f "${app}/.env.local"

    cat > "${app}/.env" <<ENVEOF
# Auto-generated by dev-local.sh – DO NOT COMMIT
# Pointing to LOCAL backend (docker-compose.dbwcare-local.yml)
DEV_API_PROXY_TARGET=http://localhost:8000
VITE_API_BASE_URL=
VITE_WEB_BASE_URL=http://localhost:3000
VITE_ADMIN_BASE_URL=http://localhost:3001
VITE_ADMIN_BASE_PATH=/god-mode
VITE_SPACE_BASE_URL=http://localhost:3002
VITE_SPACE_BASE_PATH=/spaces
VITE_LIVE_BASE_URL=http://localhost:3100
VITE_LIVE_BASE_PATH=/live
ENVEOF
    echo -e "${GREEN}✓${NC} ${app}/.env geschrieben (lokal, .env.local entfernt)"
  done

  # Live-Service .env (laeuft via pnpm dev, braucht localhost Redis + API)
  rm -f apps/live/.env.local
  cat > apps/live/.env <<ENVEOF
# Auto-generated by dev-local.sh – DO NOT COMMIT
PORT=3100
API_BASE_URL=http://localhost:8000
WEB_BASE_URL=http://localhost:3000
LIVE_BASE_URL=http://localhost:3100
LIVE_BASE_PATH=/live
LIVE_SERVER_SECRET_KEY=local-dev-live-secret
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_URL=redis://localhost:6379/
ENVEOF
  echo -e "${GREEN}✓${NC} apps/live/.env geschrieben (lokal)"
}

wait_for_api() {
  echo -e "${YELLOW}Warte auf API (localhost:8000)...${NC}"
  local retries=60
  while [ $retries -gt 0 ]; do
    if curl -sf http://localhost:8000/api/instances/ > /dev/null 2>&1; then
      echo -e "${GREEN}✓${NC} API ist bereit"
      return 0
    fi
    retries=$((retries - 1))
    sleep 2
  done
  echo -e "${YELLOW}API antwortet noch nicht – starte Frontend trotzdem${NC}"
}

smoke_check() {
  # Pruefe ob Frontend tatsaechlich gegen lokales Backend proxied
  echo -e "${BLUE}→${NC} Smoke-Check: Frontend-Backend-Verbindung..."

  local backend_id frontend_id

  backend_id=$(curl -sf http://localhost:8000/api/instances/ 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('instance',{}).get('instance_id','') if isinstance(d,dict) else d[0].get('instance_id','') if isinstance(d,list) and d else '')" 2>/dev/null || echo "")

  if [ -z "$backend_id" ]; then
    echo -e "${YELLOW}⚠${NC}  Backend antwortet nicht auf /api/instances/ – Smoke-Check uebersprungen"
    return 0
  fi

  frontend_id=$(curl -sf http://localhost:3000/api/instances/ 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('instance',{}).get('instance_id','') if isinstance(d,dict) else d[0].get('instance_id','') if isinstance(d,list) and d else '')" 2>/dev/null || echo "")

  if [ -z "$frontend_id" ]; then
    echo -e "${YELLOW}⚠${NC}  Frontend antwortet noch nicht – Smoke-Check spaeter mit: ./dev-local.sh check"
    return 0
  fi

  if [ "$backend_id" = "$frontend_id" ]; then
    echo -e "${GREEN}✓${NC} Smoke-Check bestanden: Frontend proxied an lokales Backend (Instance: ${backend_id:0:8}...)"
    return 0
  else
    echo -e "${RED}✗ FEHLER: Frontend redet mit anderem Backend!${NC}"
    echo -e "  Backend Instance ID: $backend_id"
    echo -e "  Frontend Instance ID: $frontend_id"
    echo -e ""
    echo -e "  Vermutlich hat eine .env.local in apps/web/ eine falsche URL."
    echo -e "  Loesung: ./dev-local.sh down && ./dev-local.sh up"
    return 1
  fi
}

cmd_check() {
  echo -e "${BLUE}→${NC} Manuelle Diagnose..."
  echo ""

  # Backend erreichbar?
  if curl -sf http://localhost:8000/api/instances/ > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Backend (localhost:8000) erreichbar"
  else
    echo -e "${RED}✗${NC} Backend (localhost:8000) nicht erreichbar"
    echo "  Starte Backend: ./dev-local.sh up"
    return 1
  fi

  # Frontend erreichbar?
  if curl -sf http://localhost:3000/ > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Frontend (localhost:3000) erreichbar"
  else
    echo -e "${YELLOW}⚠${NC}  Frontend (localhost:3000) nicht erreichbar"
  fi

  # Smoke Check
  smoke_check

  # Env-Files pruefen
  echo ""
  for app in apps/web apps/admin apps/space; do
    if [ -f "${app}/.env" ]; then
      local target
      target=$(grep DEV_API_PROXY_TARGET "${app}/.env" 2>/dev/null | cut -d= -f2)
      echo -e "  ${app}/.env → DEV_API_PROXY_TARGET=${target}"
    fi
    if [ -f "${app}/.env.local" ]; then
      echo -e "  ${RED}⚠ ${app}/.env.local existiert (kann .env ueberschreiben!)${NC}"
    fi
  done
}

# ── Commands ────────────────────────────────────────────────────────────

cmd_up() {
  check_env

  echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║  DBWCARE BOARD – Lokales Full-Stack      ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"

  # Backend starten
  echo -e "\n${BLUE}→${NC} Starte Backend-Services (Docker)..."
  dc up -d --build

  # Frontend .env schreiben
  write_frontend_env

  # Warten bis API bereit
  wait_for_api

  # pnpm install falls noetig
  if [ ! -d node_modules ]; then
    echo -e "${BLUE}→${NC} node_modules fehlt, starte pnpm install..."
    pnpm install
  fi

  # Frontend starten
  echo ""
  echo -e "${GREEN}Starte Frontend Dev-Server...${NC}"
  echo -e "  ${RED}web${NC}   → http://localhost:3000"
  echo -e "  ${BLUE}admin${NC} → http://localhost:3001/god-mode"
  echo -e "  ${YELLOW}space${NC} → http://localhost:3002/spaces"
  echo -e "  ${GREEN}api${NC}   → http://localhost:8000 (Docker)"
  echo -e "  ${GREEN}live${NC}  → http://localhost:3100 (pnpm dev)"
  echo ""
  echo -e "${YELLOW}Tipp:${NC} Nach dem Start in neuem Terminal: ./dev-local.sh check"
  echo ""

  pnpm dev
}

cmd_down() {
  check_env
  echo -e "${BLUE}→${NC} Stoppe Backend-Services..."
  dc down
  echo -e "${GREEN}✓${NC} Backend gestoppt"
}

cmd_logs() {
  check_env
  local service="${1:-}"
  if [ -z "$service" ]; then
    dc logs -f
  else
    dc logs -f "$service"
  fi
}

cmd_migrate() {
  check_env
  echo -e "${BLUE}→${NC} Fuehre Migrations aus..."
  dc exec api python manage.py migrate --settings=plane.settings.local
  echo -e "${GREEN}✓${NC} Migrations abgeschlossen"
}

cmd_shell() {
  check_env
  dc exec api python manage.py shell --settings=plane.settings.local
}

cmd_seed() {
  check_env
  echo -e "${BLUE}→${NC} Seede Demo-Daten..."
  dc exec api python manage.py seed_dbwcare --settings=plane.settings.local
  echo -e "${GREEN}✓${NC} Demo-Daten angelegt"
}

cmd_reset() {
  check_env
  echo -e "${RED}ACHTUNG: Alle lokalen Daten (Postgres, Redis, Minio) werden geloescht!${NC}"
  read -p "Bist du sicher? (y/N) " confirm
  if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
    echo "Abgebrochen."
    exit 0
  fi
  echo -e "${BLUE}→${NC} Stoppe und loesche Volumes..."
  dc down -v
  echo -e "${GREEN}✓${NC} Volumes geloescht"
  echo -e "${BLUE}→${NC} Starte neu..."
  cmd_up
}

# ── Main ────────────────────────────────────────────────────────────────

cmd_test() {
  check_env
  echo -e "${BLUE}→${NC} Backend-Tests (pytest)..."
  # pytest.ini setzt DJANGO_SETTINGS_MODULE=plane.settings.test
  dc exec api python -m pytest plane/tests/ -x -v 2>&1
  echo -e "${GREEN}✓${NC} Tests abgeschlossen"
}

case "${1:-help}" in
  up)      cmd_up ;;
  down)    cmd_down ;;
  logs)    shift; cmd_logs "$@" ;;
  migrate) cmd_migrate ;;
  shell)   cmd_shell ;;
  seed)    cmd_seed ;;
  check)   cmd_check ;;
  test)    cmd_test ;;
  reset)   cmd_reset ;;
  help|*)
    echo "Usage: ./dev-local.sh <command>"
    echo ""
    echo "Commands:"
    echo "  up       Starte Backend (Docker) + Frontend (pnpm dev)"
    echo "  down     Stoppe Backend-Services"
    echo "  logs [s] Zeige Logs (optional: Service-Name)"
    echo "  migrate  Django-Migrations ausfuehren"
    echo "  shell    Django-Shell oeffnen"
    echo "  seed     Demo-Daten anlegen (User, Workspace, Subscription)"
    echo "  check    Diagnose: Frontend-Backend-Verbindung pruefen"
    echo "  test     Backend-Tests (pytest) ausfuehren"
    echo "  reset    Volumes loeschen & komplett neu starten"
    ;;
esac
