#!/usr/bin/env bash
# DBW Care Board – Lokaler Dev-Server
# Startet web, admin und space mit Hot-Reload gegen das Hetzner-Backend.
# Usage: ./dev.sh

set -euo pipefail
cd "$(dirname "$0")"

# ── Farben ──────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   DBWCARE BOARD – Lokale Entwicklung     ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"

# ── Env laden ───────────────────────────────────────────────────────────
if [ ! -f .env.local.dev ]; then
  echo -e "${RED}Fehler: .env.local.dev nicht gefunden!${NC}"
  echo "Kopiere .env.local.dev.example oder erstelle die Datei manuell."
  exit 1
fi

set -a
source .env.local.dev
set +a
echo -e "${GREEN}✓${NC} Umgebungsvariablen aus .env.local.dev geladen"
echo -e "  API-Proxy: ${YELLOW}${DEV_API_PROXY_TARGET}${NC} (via Vite Proxy)"

# ── .env in App-Ordner schreiben (Vite liest nur die eigene .env) ──────
# turbo startet Vite in Sub-Prozessen – ENV-Variablen aus dem Parent
# kommen nicht zuverlässig an. Deshalb schreiben wir sie direkt.
for app in apps/web apps/admin apps/space; do
  cat > "${app}/.env" <<ENVEOF
# Auto-generated by dev.sh – DO NOT COMMIT
# Loaded from .env.local.dev
DEV_API_PROXY_TARGET=${DEV_API_PROXY_TARGET}
VITE_API_BASE_URL=${VITE_API_BASE_URL:-}
VITE_WEB_BASE_URL=${VITE_WEB_BASE_URL:-http://localhost:3000}
VITE_ADMIN_BASE_URL=${VITE_ADMIN_BASE_URL:-http://localhost:3001}
VITE_ADMIN_BASE_PATH=${VITE_ADMIN_BASE_PATH:-/god-mode}
VITE_SPACE_BASE_URL=${VITE_SPACE_BASE_URL:-http://localhost:3002}
VITE_SPACE_BASE_PATH=${VITE_SPACE_BASE_PATH:-/spaces}
VITE_LIVE_BASE_URL=${VITE_LIVE_BASE_URL:-http://localhost:3100}
VITE_LIVE_BASE_PATH=${VITE_LIVE_BASE_PATH:-/live}
ENVEOF
  echo -e "${GREEN}✓${NC} ${app}/.env geschrieben"
done

# ── pnpm install falls noetig ───────────────────────────────────────────
if [ ! -d node_modules ]; then
  echo -e "${BLUE}→${NC} node_modules fehlt, starte pnpm install..."
  pnpm install
fi

# ── Dev-Server starten ──────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Starte Dev-Server...${NC}"
echo -e "  ${RED}web${NC}   → http://localhost:3000"
echo -e "  ${BLUE}admin${NC} → http://localhost:3001/god-mode"
echo -e "  ${YELLOW}space${NC} → http://localhost:3002/spaces"
echo ""

# turbo run dev startet alle apps parallel mit farbiger Ausgabe
pnpm dev
